day: "gün"
hour: "saat"
minute: "dakika"
second: "saniye"
hourOffset: 3
commands:
  '17:00':
    - "say Event bir saat sonra başlayacaktır!"
  '17:50':
    - "say Event 10 dakika sonra başlayacaktır!"
  '18:00':
    - "say Saat 18.00!"
    - "say E V E N T    Z A M A N I"
    - "superEventCommand"